[package]
name = "keyeater/keycamera"
version = "1.0.1"
license = "MIT"
authors = ["keyeater"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = ["src", "src/*", "default.project.json", "wally.toml"]


[dependencies]
